### ISSUE TITLE
[ED][Project Plan] Edit to Goal for clarity and punctuation

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-roles-responsbilities#1]
Suggested rewrite:
The project goal is to define an adaptive framework that will guide stakeholders to integrate web accessibility in all relevant aspects of project lifecycles while taking ownership of design and development decisions related to creating accessible content. 

Could be broken into shorter sentences but I was unsure if you intended it to be just one. if two sentences, maybe something like this:
Our goal is to define an adaptive framework that will guide stakeholders to integrate web accessibility in all relevant aspects of a product or project life cycle. The result will allow users to take ownership of design and development decisions related to creating accessible content.

**Comment by bakkenb** [comment]
Agree. This is a big concept sentence to understand. Would be even better if it was broken into a few more simple sentences, but still being one cohesive goal.

**Comment by dboudreau** [comment]
@sharronrush - Yes, of course. We can break it down that way. I would normally have used Hemingway app to rework the content, but ran out of time to do so. We should probably do that next.

**Comment by dboudreau** [comment]
Change made to project plan. Looks like I can't close issues myself, so I'll leave it for someone else to close.

**Comment by dboudreau** [comment]
Closing, now that I have god-like powers. :godmode:
