### ISSUE TITLE
[!!][Roles Definition] User Research

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-roles-responsbilities#12]
The designer tasks is missing the creation of empathy maps.  The design team may also create empathy maps to show what users thinks, feels, does, and says. It is done more in the research phase, and typically involves the whole team.  It is an especially useful exercise in an agile development environment.  Here's a link to a resource from the Nielsen Norman Group [Empathy Mapping: The First Step in Design Thinking](https://www.nngroup.com/articles/empathy-mapping/).

**Comment by dboudreau** [comment]
@maryjom - You raise good points. As a matter of fact, when it comes to UX mapping methods, we could add more than empathy mapping: there's also user journey mapping, experience mapping and service blueprinting, just to name a few: https://www.nngroup.com/articles/ux-mapping-cheat-sheet/.

I'd tend to associate all 4 methods to UX Researcher, would you agree?

**Comment by dboudreau** [comment]
Closing, as per comment in issue #13. Also added some of those tasks to the role. Please bounce back if you feel something is missing. :)
