### ISSUE TITLE
[!!][Roles Definition] User Experience Design

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-roles-responsbilities#13]
It isn't quite obvious though you do say one of the UX designer's tasks is to design the workflow.  To me this should/could be further described.  It isn't just the mouse-operated workflow, but would include the touch workflow (in the case of mobile devices), the voice-operated workflow (if there is one), and the keyboard workflow.  

For individual custom interactive UI widgets, interaction designers should also design the keyboard interaction for operating all of the functionality of the widget.  To me, this is super important because new/custom widgets often fall down in this regard.  It is also an area where prototyping and user testing is really beneficial to make sure the operability of the content via keyboard is efficient.

**Comment by bakkenb** [comment]
+1

**Comment by orvalle** [comment]
I think of those as operation and interaction at a finer grain level than as described. Covering that as an additional bullet would be a good idea to separate it from the higher level business process / workflow that I associate with those terms.

**Comment by Sean-Kelly** [comment]
I'm reading "process maps" here as more like "user journey map".

**Comment by orvalle** [comment]
We can add "etc." or "et al." to cover a lot of the additional items We don't want to go into too much detail some roles and not others. 

As we've discussed in EO meetings, a role definitions document is a useful product itself. However for our project it's just a starting reference so people can identify themselves how our work applies to theirs.

**Comment by dboudreau** [comment]
I've added a comment in issue #12 that goes along the same lines... we could be more specific, but at some point we're still going to miss something. The list is not meant to be exhaustive, its meant to sort of frame the types of activities the role is involved in, for the most part. 

I'm going to close this one, but if anyone feels a particular tasks needs to be added to a particular role, just let us know and we'll add it. Our goal is to define set of high-level tasks, not more. So we can focus on the actual work, which is defining what part of accessibility are owned by each of these roles. :)
