### ISSUE TITLE
[ED][Roles Definition] Content Creation Tasks & Job Titles

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-roles-responsbilities#14]
As a suggestion, consider adding one or more of these: "alternative text, headings, labels" to the list in the first bullet.  I realize you're not creating an exhaustive list, but these are also important because WCAG requires them to be meaningful.  To me, whomever is creating the content should design the information to represent the intent/meaning for the particular element.

What about product documentation? Enterprise level applications don't just have help, they've often got additional web-based documentation that goes with the application.
 
For the Job titles section for this role (since they're writing help and I would expect also documentation?) In IBM we call this an Information Developer and outside IBM the role is a technical writer. Wikipedia lists more alternate job titles for a [technical writer](https://en.wikipedia.org/wiki/Technical_writer).

**Comment by bakkenb** [comment]
I had a similar thought when reading the first bullet. "Writes Content" is straight forward, but then the exempli gratia (e.g.) only lists "help text, error messages" and it makes me think this is not about writing the main content but the additional (for lack of a better word) "ancillary" content. Maybe add "text" or "copy" or something that refers to the bulk of the content they write.

In addition to Mary Jo's titles, I would add Content Developer.

**Comment by AndrewArch** [comment]
so, maybe we need to mention 'main content' and 'micro content' rather than specific examples (that will always exclude something)

**Comment by orvalle** [comment]
I definitely agree about adding technical writer. I’ve worked with many in the past.

Calling out help support systems and content would be a good addition.

**Comment by dboudreau** [comment]
Changes made. Please review.

**Comment by bakkenb** [comment]
+1 to the edits. Looks great.
