### ISSUE TITLE
[ED][Roles Definition] Front End Development

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-roles-responsbilities#15]
I don't see WAI-ARIA mentioned anywhere in this section.  While I admit that they would be encouraged to use native elements as much as possible, any custom scripting of interactive elements will need WAI-ARIA to be accessible.

Perhaps it could be covered in an in additional bullet that is something like: Using programming practices known to make accessible content (e.g. built-in accessibility tagging, WAI-ARIA as needed, etc.)

**Comment by orvalle** [comment]
That makes an assumption that they know WAI-ARIA. My experience is that is typically not true at this time. Covering that as supplemental training would be part of our recommendations.

**Comment by dboudreau** [comment]
Added "Coding interactive elements/widgets using WAI-ARIA" as a new bullet to the list. I don't know that we had intentionally excluded aria from the list... I think we just didn't consider it much when we initially came up with it. True, not every developer will know about WAI-ARIA, but that's true of most things or technologies... devs may not know about such and such framework, or library. Some devs don't even know about HTML semantics, but we're still going to mention those things. :)
