### ISSUE TITLE
[ED][Roles Definition] Back End Development

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-roles-responsbilities#16]
It isn't quite obvious what the Back-end developer's real role is in accessibility as there's not enough detail for me.  When I think about CMS used in back-end development, if there's a database used to store the content to programmatically build a website then the back-end developer has to architect the DB to contain any accessibility information needed for the front-end.  

Example: a shopping website that pulls information and pictures of items for sale out of a database. In this case content elements, like images of products, would have to have the alternative text also stored in the DB.  This has to be architected into the DB structure/information stored.

I'm just wondering if there's a way to make this more clear/obvious when the back-end developer actually has to do something for accessibility. 

This may be getting off in the weeds, but there may also be considerations for data used in Artificial Intelligence (AI) used by the website.  Any data stores used for AI should be checked to ensure there isn't bias against persons with disabilities that would unintentionally prevent proper usage of the content or introduce any discrimination.

**Comment by dboudreau** [comment]
I've added "Architecturing accessibility considerations into the database structure/information stored" as a new task, though we felt this was implicitly covered in the first - though admittedly extraordinarily vague - bullet (Database architecture and optimization).

I get what you'Re saying about back-end devs... I may be wrong, but I'm really looking at accessibility implementations as something that happens mostly on the front-end side of things... at least on the surface. I'm not sure it's worth getting to the level of depth that would be needed to see actual impacts for back-end developers, beyond the few Success Criteria/considerations we'll identify down the road for this role.

But if you have specific suggestions, we're interested. Let's use this issue to flesh those out.

**Comment by dboudreau** [comment]
@maryjom Any feedback to add to this issue? Do you still feel strongly about this? Two years later, we still feel BED don't play a particularly active role In the accessibility implementation and this is still reflected in our decision tree.

**Comment by maryjom** [comment]
@dboudreau I agree, they don't play an active role. Accessibility is primarily a FED and designer thing.

**Comment by dboudreau** [comment]
@maryjom Awesome, then we're on the same page. Thanks for following up. :)
