### ISSUE TITLE
[ED][Roles Definition] Project Manager

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-roles-responsbilities#18]
Typical job titles: We also call Project managers "Offering Managers" that manage the schedules/project management work, but I think that's a purely IBM thing.

Also, I don't see a Business Analyst as having the same job role as a Project Manager so I don't understand it as being an equivalent job title for this role.  Check out the definitions of both roles in wikipedia:  [Project manager](https://en.wikipedia.org/wiki/Project_manager) and [Business Analyst](https://en.wikipedia.org/wiki/Business_analyst).

**Comment by bakkenb** [comment]
Agree. At Pearson, a Project Manager and a Business Analyst have two very different functions.

**Comment by dboudreau** [comment]
Fair enough. Do you feel another category or role needs to be added specifically for business analysts?

**Comment by Sean-Kelly** [comment]
Put BA under Product manager?

**Comment by dboudreau** [comment]
For the time being, based on the definitions you've provided, we're moving BAs under the product manager role. Eager to hear your thoughts is you feel otherwise. :)

**Comment by orvalle** [comment]
We have BA under **Project** Manager but it fits better under **Product** Manager. Agreed.

**Comment by bakkenb** [comment]
+1
