### ISSUE TITLE
[!!][Roles Definition] Back End Development

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-roles-responsbilities#19]
I don't particularly like starting the role definition with "It’s likely that a back end developer will not be directly involved in the work needed to make a product accessible."

I think this statement will immediately give people who consider themselves back end developers an out, or an excuse to say accessibility is not my issue/problem to deal with. It is someone else's role.

I understand what is trying to be communicated here but I think it needs to be said in a different manner to let those reading know that yes, they have a part to play too even though it may be smaller. Just an idea to start from... "Back end developers have a smaller, more indirect involvement with accessibility work, but it is still a critical role that plays a part in delivering and accessible product."

**Comment by orvalle** [comment]
That’s a nicer way of covering the fact that back end development has little direct impact on UX design decisions in general and less about those that impact a11y.

**Comment by Sean-Kelly** [comment]
It's a good thought—keep them reading even if the cases where they would be involved are few.

**Comment by dboudreau** [comment]
Yup, ok. Good points. New wording says: "Back end developers have a smaller, more indirect involvement with accessibility work, but still play a critical role in delivering accessible products, as the underlying product architecture can inform accessibility solutions."
