### ISSUE TITLE
[ED][Roles Definition] "User researchers often don’t do much" :-)

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-roles-responsbilities#20]
The sentence "User researchers often don’t do much – if any – design" reads oddly to me:

1. The hyphenation makes me parse the first part as "User researchers often don’t do much", then it takes me a while to figure the connection to "design" later.
2. This then makes me wonder, do user research develop, test, or manage? Why is only design mentioned?

I suggest removing this sentence because it is too confusing, especially as a first sentence. If it is essential, then it should be edited to be less confusing in reading order (eg. "User researchers often don’t do much design, if any" or such).

**Comment by bakkenb** [comment]
+1

**Comment by shawna-slh** [comment]
+1

Also, better to put positive description first.

**Comment by dboudreau** [comment]
Fair enough. Made change to now say "User researchers have a smaller, more indirect involvement with design, but still play a critical role in designing accessible experiences."
