### ISSUE TITLE
[ED][Roles Definition] smaller shops

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-roles-responsbilities#21]
Replace "particularly in smaller shops" with "particularly in smaller projects"?

**Comment by dboudreau** [comment]
Done.

**Comment by Sean-Kelly** [comment]
It's been my experience that this has more to do with the size of the group (the "shop") than with the project.  Most groups I've worked with don't realign/combine/uncombine people and roles against the size of the project.

**Comment by orvalle** [comment]
Smaller "teams" is more correct.

**Comment by dboudreau** [comment]
Changed again to reflect Sean's comment. It now says "particularly on smaller teams or smaller projects" to account for both perspectives.
