### ISSUE TITLE
[ED][Roles Definition] see vs interact?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-roles-responsbilities#22]
I stumbled over "as an end user would see it" -- but we are talking about look and *feel*, not only look. Maybe "as an end user would perceive/interact with/encounter it"? I'm not very fond of these terms but they work better for me than the word "see". Maybe someone else has better ideas...

**Comment by dboudreau** [comment]
Good catch. Changed "as an end user would see it" by "as an end user would experience it, visually or otherwise".

**Comment by nitedog** [comment]
Works for me. Could do without the "visually or otherwise" too, in my opinion.

**Comment by dboudreau** [comment]
I see what you mean, but I'm uncomfortable with purposefully avoiding any reference to the word visual. We don't need to be holier than thou. Blind people talk about seeing all the time. Will close to one off for now. :)

**Comment by nitedog** [comment]
I didn't suggest this because of what I think blind people may think, I just find it superfluous :-)

**Comment by dboudreau** [comment]
Fair enough. :)
