### ISSUE TITLE
[ED][Roles Definition][later] Copyedit pass

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-roles-responsbilities#24]
I think this is a very well written draft overall.

Later when we're getting closer to calling it done, it would be good to get an editor to do a copy edit pass with the [Style Guide](https://www.w3.org/WAI/EO/wiki/Style) in mind.

**Comment by dboudreau** [comment]
Great idea. We'll do, as we usually do for any document we create in EO. :)
