### ISSUE TITLE
[ED][Roles Definition] Project Manager and Product Manager, User Researcher

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-roles-responsbilities#25]
Without thinking about it a lot, I don't see significant difference between Project Manager and Product Manager in terms of the WCAG SCs that they are responsible for.  I also note that Denis' previous [ARB](https://www.w3.org/community/wai-engage/wiki/Accessibility_Responsibility_Breakdown) roles didn't have them separated.

Perhaps for simplification we want them combined?

I don't feel strongly at all, and am fine with separate roles if it turns out that it is good for the mapping.

(Possibly leave as an open question for now, and they see when you're mapping them how it plays out?)

... /me looks closer at the ARB and sees N/A for the SC mapping ...

So I'm not sure how the Manager roles fit in the SC mapping at all. Maybe we want to include general info on their roles in accessibility, but it doesn't fit in the SC mapping table?

If so, is it important to have them as separate roles?

**Comment by shawna-slh** [comment]
Actually, I think there is a similar issue with "User Researcher" -- that is, yes, they have a *very* important role in accessibility, but they aren't responsible for getting specific SCs implemented.

**Comment by orvalle** [comment]
I think the definitions for project and product managers are significantly different. I also see the product manager as possibly having input to design decisions. The project manager probably not.

**Comment by Sean-Kelly** [comment]
I'd have to agree about the differenced between the Prod Manager and the Proj Manger are pretty different in my experience.

**Comment by dboudreau** [comment]
We feel like both are very different. One is not a duplication of the other in any way. They're both manager roles, yes, but focused on different aspects of the project. We prefer to keep them distinct. The list that will come up for each will help make them feel more distinct. Stay tuned!

**Comment by shawna-slh** [comment]
I totally agree that the roles are different -- I just didn't think that they will need different columns in the SC mapping -- and then when I thought about it more, **I don't see that they will be in the SC mapping at all**.

Same with "User Researcher".

I'm OK with leaving them as is, since we envision that this doc can be useful beyond the SC mappping.

**Comment by dboudreau** [comment]
I actually expect them to be at the top level, but we can talk about that when we get there. :)
