### ISSUE TITLE
[ED][Roles Definition] scope disqualifier

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-roles-responsbilities#26]
Do we need this sentence?:
> Native mobile, desktop software and other digital formats such as PDFs and ePUBs are not specifically addressed in this document, but many of the principles still apply.

If we *were* addressing these, would the document be any different?

If not, can we just delete the sentence?

**Comment by dboudreau** [comment]
Fair enough. We can remove it. The rationale behind it was that some of those technologies are inherently different than web content (e.g. native mobile), but most aspects will still apply as per Success Criteria intents. We might get back to it eventually, but removing the sentence will not affect what our deliverable will look like.
