### ISSUE TITLE
Question on checkpoint Masterlist IMG-003

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-roles-responsbilities#27]
https://www.w3.org/WAI/EO/wiki/Accessibility_Checkpoint_Master_List

IMG-003 "I want "null" alt attributes (using alt="") to be used for images that are already described in text in adjacent page content."

This one seems like a Design > Content Owner decision that is provided to the Implementation > Front End Developer.

**Comment by dboudreau** [comment]
@lakeen it looks as though you may be looking at a different version of our document? Can you please refer to https://www.w3.org/WAI/EO/wiki/Accessibility_Checkpoint_Master_List and double-check?
