### ISSUE TITLE
[ED][Project Plan] Requirements

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-roles-responsbilities#3]
Seems like we could take a first pass at the requirements. If an example would help, here is one:
https://www.w3.org/WAI/EO/wiki/Feature_requirements_for_Interactive_Guide_to_Assist_Managing_Web_Accessibility_Evaluations

To begin, it may be something as simple as further expounding on the stated deliverables. For example:

1.The role definition document must
- identify/define key stakeholders according to roles within the lifecycle of product or project development
- clarify that not all roles will be represented in all projects
- provide guidance on how to use the matrix
- ...@@
2. Criteria ownership matrix must:
- specify typical status of above defined roles in the project lifecycle (primary, secondary, informed),
- create easy to use grid for each of the defined roles
- map WCAG SCs and techniques to role-specific tasks within the grid
- include one-page, ownership assignments per WCAG criteria that states which roles should be involved, and to what degree,
- provide sample checkpoints that prioritize responsibilities based on WCAG Success Criteria and who it refers to (for internal reference),
3. The Decision Tree must:
- present a series of Yes/No questions to lead the user through a process
- be customizable
- ...@@

**Comment by dboudreau** [comment]
@sharronrush - I'm all in. Whatever makes the document more straightforward and more digestible for the intended audience is good in my book.

**Comment by dboudreau** [comment]
@sharronrush Do you still feel the same way about the resource, or have our changes from the past two years addressed your concerns? I'd like to either revive or close this issue in the near future.

**Comment by sharronrush** [comment]
Happy to close the issue
