### ISSUE TITLE
[ED-med] [ARRM Survey Results] [6. Role Definition]: Again to colloquial

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#31]
Original comment:

> [ED-med]: Again to colloquial: “Without further ado, let's jump right in”

Resolution: Removed from document.

**Comment by dboudreau** [comment]
The content has been modified according to comment. Please go back to the document is you want to look at the change.

https://www.w3.org/WAI/EO/wiki/Role_definition_document
