### ISSUE TITLE
[ED-low] [ARRM Survey] [6. Role Definition]: Main focus design:

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#32]
Original comment:  
> [ED-low]: Main focus design: I would disagree with the focus for the design group – design decisions are not made by this group but informed by this group, supported by evidence, and decided upon by the product owner if necessary. I would drop the ‘decision’. This then aligns with ‘development’ and ‘testing’.

Resolution: After review this comment was considered a non-issue and left unchanged.

**Comment by dboudreau** [comment]
Following internal discussions, we've decided to not address this one as it was identified as editors' discretion (low).
