### ISSUE TITLE
[ED-low] [ARRM Survey Results] [6. Role Definition]: Main focus business: 

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#33]
Original comment:
> [ED-low]: Main focus business: Not sure about ‘business vision’ as the qualifier for this group. For some of the roles, yes, e.g. product owner, but I wouldn’t see vision as the role of a BA.

Resolution: Updated text to "Business Vision, Rules & Requirements"

**Comment by dboudreau** [comment]
Content changed according to Kevin's comment.
