### ISSUE TITLE
[ED-low]  [ARRM Survey Results] [6. Role Definition]: Example job titles for BA: 

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#34]
Original comment:
> [ED-low]: Example job titles for BA: I have never seen a BA being called anything other than a BA. Certainly not “Business Owner, Client Sponsor” – those would be much more ‘Client’.

Resolution: Upon review left unchanged since other names have been used.

**Comment by dboudreau** [comment]
After deliberation, we decided not to make any changes to the content, as this was identified as an editors' discretion (low) comment.
