### ISSUE TITLE
[ED-low]  [ARRM Survey Results] [6. Role Definition]: Management roles:

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#35]
Original comment:
> [ED-low]: Management roles: Not sure the final sentence, beginning “The former has more impact…”, in the role description is required at all. It is possibly contradictory and I don’t think it adequately recognises the impact that a PM or Scrum master can have in deprioritizing accessibility when delivery pressures hit.

Resolution: Revised content for Management roles description, spreading content under roles themselves

**Comment by dboudreau** [comment]
Significant changes made as a result of the comment. Thanks!
