### ISSUE TITLE
[ARRM Survey Results] [6. Role Definition]: Visual Layout

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#36]
Original comments
> The visual layout of the page is so distracting to me that I have trouble reading the content. I'm looking at it on chrome on a Mac, and it's strangely formatted. I will return to look at on a different browser.

> This page does really badly flow, and especially on mobile. Please make sure the page is readable by CSUN.
> - It took me quite some time to identify what the hierarchy of the different information is.
> - Again, I think having a broad overview page and splitting the specifics up might be easier to digest.

Resolution: Need input from Denis about final formatting

**Comment by dboudreau** [comment]
+ee@w3.org - The visual layout is temporary, and will no longer be relevant as we move the content over to the EO site, so we'll let it go for now.
