### ISSUE TITLE
[ARRM Survey Results] [6. Role Definition]: Wall of Text

### ISSUE THREAD

**Issue by orvalle** [w3c/wai-roles-responsbilities#37]
Original comment:
> I love this cross-section view and appreciate the way the job titles are put in context and guidance is given that whatever they may be called in your org, think about the task. Again however, we are trying hard to avoid our historical tendency of posting a wall of text so try to consider ways to shorten sentences, use bullets and generally tersify. Avoid repetition. Strive for brevity and clarity.

Resolution: TBD, maybe take Sharron's offer to edit content

**Comment by dboudreau** [comment]
@sharronrush Can we work with you to make improvements on this, and get a sense of what you're looking for? Thanks.

**Comment by dboudreau** [comment]
@sharronrush - Based on our previous conversations, I'm going to close this issue and we'll work with you to improve the content in the next few weeks. :)
