### ISSUE TITLE
 [ARRM Survey Results] [5. Role-Based Decision Tree]: Agile is different

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#38]
Original comment: 
The decision tree looks good but for a more traditional development process. An agile process would have a different approach to ownership.  I know you use the terms "often" for the roles and relationships but it could be helpful as a note. I feel the end infers this and the main document is not stating it is a traditional process like waterfall, but maybe a note to outline the variations could help teams using different approaches?

**Comment by dboudreau** [comment]
@helenburge - Would you like to provide us with an example of how you would envision this so we can maybe make a change? We're happy to consider any changes if you are willing to flesh out your perspective for us.

**Comment by dboudreau** [comment]
Note - Emailed Helen directly to let her know of this issue.

**Comment by HelenBurge** [comment]
Looking at the overall role based decision tree, it is not either methodology. It is about the type of work it is and who owns that work. Agile is the same as waterfall in the fact you have the same roles in the team, but the way the work is done varies. However, the primary owner descriptions are more for how the waterfall roles work. I think we could do a description for Waterfall roles, and a description for Agile roles to help reduce the possible confusion.

**Comment by dboudreau** [comment]
@HelenBurge Would you be willing to take a stab at it, so we can see what that could look like?

**Comment by HelenBurge** [comment]
@dboudreau - sure, won't be in time for the meeting tomorrow but will work on this.

**Comment by dboudreau** [comment]
@HelenBurge - Gentle reminder! ;)

**Comment by HelenBurge** [comment]
An example would be updating:
QA Testing as Primary Owner
QA Testers are not typically part of the design or implementation process. Though they are essential or key to returning findings or feedback to respective owners for remediation, they are not likely to be identified as primary owners for any specific accessibility task, except actual testing.

To:
QA Testing as Primary Owner
QA Testers are not typically part of the design or implementation process when using a Waterfall methodology. Though they are essential or key to returning findings or feedback to respective owners for remediation, they are not likely to be identified as primary owners for any specific accessibility task, except actual testing. 

When using an Agile methodology, QA Testing is through the whole process. Testing the designs in initiation, checking code logic expectations in development, and finally checking the implementation does not introduce any unforeseen errors. By testing each item throughout the process they help take ownership of the final product, and reduces time overheads for the final stage of delivering the product.

**Comment by dboudreau** [comment]
Thanks @HelenBurge. 

I'll bring this up to the team, and we'll see how we can leverage your suggestion to improve the resource. :)

**Comment by dboudreau** [comment]
Closing this issue as some changes were made back 2020-2021 and th purpose of this resource is not to go in depth in the distinctions between agile and waterfall methodologies.
