### ISSUE TITLE
[ED-low] [ARRM Survey Results] [3. Background: Requirements Analysis]: Difference "web" and "digital" accessibility

### ISSUE THREAD

**Issue by JenniferChadwick** [w3c/wai-roles-responsbilities#39]
Original comment:

[ED-low]: There is one reference to "web accessibility" and one to "digital accessibility". Not sure that they are the same thing exactly so it might be worth settling on one.

Resolution:

[Jenn] Consider choosing one term and making it consistent throughout.

**Comment by Sean-Kelly** [comment]
do we have a preference which one?

**Comment by dboudreau** [comment]
+kevin@dewoollery.co.uk After some discussions, we've decided to standardize and stick to "web accessibility". We'll consider expanding to "digital" when WCAG 3.0 is upon us and we're clearly approaching accessibility from a broader perspective.
