### ISSUE TITLE
[ARRM Survey Results] [3. Background: Requirements Analysis]: Audience

### ISSUE THREAD

**Issue by JenniferChadwick** [w3c/wai-roles-responsbilities#40]
Current text from the [ARRM Project page](https://www.w3.org/WAI/EO/wiki/ARRM_Project_-_Accessibility_Roles_and_Responsibilities_Mapping#Audience) :

_**Audience**
The intended audience for this project could be as diverse as the cross-functional teams involved in any given project lifecycle, but the project will focus on a series of predefined roles as a starting point. While the focus of this project is on those roles that directly impact digital accessibility, it will define and assign levels of accountability for the WCAG success criteria associated with the design decisions they currently make - often without realizing their impact on people with disabilities.”_

Original comments:

Comment 1: [ED-med]: Audience - There doesn't seem to be much clarity on who the audience is. It could be much more definitive in terms of who will read it. This section also seems to blend in some content related to goals.

The audience part of the document, could start with a simple sentence like: "The primary audience is anyone that works in Information Technology." and then add the rest to expand on the detail. I feel that audience and purpose are using quite complex descriptions that could lose some of the intended audience.

Comment 2: I find the audience section too wide. If we think the audience really is "as diverse as the cross-functional teams involved in any given project lifecycle", I would try to precise it a little bit. I also think we can avoid repetition in the rest of the sentences of this paragraph. We could summarize these sentences a bit, like:

Any cross-functional team involved in a given project lifecycle where accessibility may be implemented. The project will define and assign levels of accountability for the WCAG success criteria associated with the decisions currently made by predefined roles. The project would help these roles realize their impact on people with disabilities.

Comment 3: The audience part of the document, could start with a simple sentence like: "The primary audience is anyone that works in Information Technology." and then add the rest to expand on the detail. I feel that audience and purpose are using quite complex descriptions that could lose some of the intended audience.

Resolution:

[Jenn]  I’m happy with an edit that incorporates the feedback.  Added a list of the roles (in response to one comment) and revised the sentences as per another suggestion.   I would not say “anyone working in IT” as IT has broader contexts for me (i.e. not the guy or gal who fixes your computer) (comment 3).

[Jenn] Suggested edit:

**Audience**

[Jenn] _The intended audience for this project is any cross-functional team involved in a given project lifecycle where accessibility may be implemented into websites:
Project Manager, Designer, Developer, Content Author, Quality Assurance (QA) Tester.

[Jenn] The project will define and assign levels of accountability for the WCAG success criteria associated with the decisions currently made by predefined roles. The project would help these roles realize their impact on people with disabilities.

[Jenn] It includes examples of responsibilities, or taskpoints, that may be assigned to each role in the team in order to cover, and meet, specific WCAG Success Criteria._

**Comment by dboudreau** [comment]
+helen.burge@deque.com
@daniel-montalvo 
+kevin@dewoollery.co.uk 

After some consideration, we decided that because this page in only meant for internal consumption and that it will never find its way into the EO site, that this is not worth editing. We recognize the value of your comments and as we create new content intended for the public as part of the introduction resource, we'll make sure to clarify our position, but foe this one document, because it's all meant to be internal, we are not going to make any changes. Thank you.
