### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: Change task point to checkpoint

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#45]
original comments:
Eric:
What is a task point? Is it a task?

Kevin
[ED-med]: Purpose: It might seem strange but I am not clear on the purpose of this document particularly. I think this is tied within the thoughts I raised regarding the definition of ‘task point’. If task point is a user story then this document is a description of how to apply RACI. If task point is a Success Criteria (or a facet of one) then the Accessibility Checkpoint Master List has done the job of assigning responsibility – which is why I am a bit unclear on the purpose of this document.
[ED-med]: Tasks and task points: I am not sure about these terms and their usage. The Accessibility Checkpoint Master List doesn’t really define tasks, it is more a series of requirements or checks. Introducing ‘task’ and ‘task point’ seems to just add more unexplained terminology.
[ED-high]: Task point: If the above is rationalised, then there really needs to be a description of what is meant by a ‘task point’. It is a key aspect to the decision tree but isn’t really explained. Actually, thinking about it I have no idea what a task point is, how it relates to a checkpoint or accessibility and I don’t know that the examples in each section help explain this at all.
[ED-high]: Examples 1 and 2 Checkpoints: Ok, starting to get more of an understanding of ‘checkpoint’/’task point’ (although the terminology seems to be being used interchangeably which isn’t really helping). These statements seem to be more akin to user stories, although they are not formulated as such. Might it not be better to simply state these as user stories – that would align more with actual good practice than ‘want’ statements?

**Comment by dboudreau** [comment]
+kevin@dewoollery.co.uk
+ee@w3.org
@slhenry (cc'ed)

The whole taskpoint vs checkpoint issue stems from initial discussions involving Shawn about the use of "checkpoints" and how that might confuse some people who still live in a world where WCAG 1.0 has any kind of relevancy. Checkpoints is still today our preferred label for these things, but we'll have to revisit that question at some point. Especially if it gets reintroduced somehow in WCAG 3.0/Silver...

**Comment by mgifford** [comment]
@shawna-slh any clarity on this?   
  
This feels too into the weeds for me, or to tied to a conversation that someone had in 2020.   
  
I suggest we close this issue unless we can get some additional clarity from Kevin, Eric, Lewis or Shawna.
