### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: [ED-low]: Primary ownership – Step 1: Branding guidelines should be visual design.

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#46]
original comment:
Branding guidelines are more in the realms of visual design.

**Comment by cochfarf** [comment]
Branding guidelines for this purpose are considered those aspects of the design that are being imposed from outside the project that the development team must adhere to and now something that the visual designer may change.

**Comment by dboudreau** [comment]
+kevin@dewoollery.co.uk Good point. We've made some changes to reflect the reality of organizations that may have smaller teams as well, where these decisions are not all driven by the business.

**Business analysis examples include**
<ul>
<li>Providing functional business requirements and features,</li>
<li>Specifying additional technical requirements (legal, financial, security, etc.),</li>
<li>Administering branding guidance and standards,</li>
<li>Defining core features and high-level product functionalities,</li>
<li>Etc.</li>
</ul>

*Visual design examples include:*
<ul>
<li>Making presentation choices such as color, font, layout, spacing, etc.,</li>
<li>Adapting branding guidelines and related brand variations,</li>
<li>Documenting and defining presentation through styleguides,</li>
<li>Designing hi-fidelity mock ups and comprehensive layouts (comps),</li>
<li>Etc.</li>
