### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: [ED-high]: Primary ownership – accessibility is a non-functional requirement

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#47]
original comment:
Primary ownership – Step 1: I am not sure that business and non-functional requirements can be grouped in this way. Accessibility is, arguably, a non-functional requirement. This would mean that every single task point is driven by a non-functional requirement.

**Comment by dboudreau** [comment]
@iadawn It may be that you're approaching "primary ownership" in a different way than the one we intend. There's a difference between "ownership of the project" (which looks like this is what you may have in mind here) and the primary ownership of any given task itself within a project (which is what we mean in this resource). What we are talking about - or focusing on - is the **person** who has ownership of the decision process or the task to be completed - who's ultimately both **accountable** and **empowered** to make a decision.

Does that change your perspective and understanding? Does this make sense?

To add to the discussion (for everyone's benefit - **functional vs non-functional reqs**):
Functional requirements are product features and focus on user requirements, defining what the system does or must not do. In comparison, non-functional requirements specify how the system should do the thing that the functional requirements define, and do not affect the basic functionality of the system.

**Comment by mgifford** [comment]
@cochfarf if this clarifies your concerns, please let us know. If not, Please tell us why.   
  
If not we should close this issue.
