### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: [ED-low]: description of longdesc imprecise

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#49]
original comment:
longdesc description: This could be read as putting the descriptive content in the longdesc attribute rather than as a link.

**Comment by dboudreau** [comment]
+kevin@dewoollery.co.uk After reviewing the document, we could not find any occurrences of "longdesc" anywhere in the decision tree document. Can you please provide additional guidance to help us locate that particular passage? It may be that it was pruned in a previous review, but we honestly can't remember by now. As of today, unless you get back to us with some additional context, we'll just close this one and move forward.
