### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: Confusion of using Steps 1-7 and A & B

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#51]
original comment:
- I don’t understand why Secondary owner is step A, contributors is B and primary is 1–7. Shouldn’t selecting the primary owner be Step A?
- description to get an idea of what is happening first. It is a lot, and it is very abstract. It’s probably quite hard to weave an example through it narratively, but I think that would help the understanding.

**Comment by dboudreau** [comment]
+ee@w3.org Very good point, sir! We've made a few changes in the structure of the document to reflect this, and now find ourselves with a 3-step process we didn't even know we had! So thank you for that. :) 

Changes made right into the document already.
https://www.w3.org/WAI/EO/wiki/Role-Based_Decision_Tree
