### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]:  Too many headings in page

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#52]
original comment:
40 headings on one page is just overwhelming, it would probably be beneficial to split the document up.

**Comment by dboudreau** [comment]
Very good observation. We've revisited the page, and reduced the number of headings considerably, by simplifying the structure of the document. Would love to hear your thoughts about the resulting structure, +ee@w3.org
