### ISSUE TITLE
[!!][Project Plan] In Scope unclear

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-roles-responsbilities#6]
The things in scope don't seem to match the deliverables.

> In Scope
> * Process definition
> ** Role selection, creation of UX decision tree, ttesting of decision tree to create RACI matrix and related sample materials.

What do you mean by "process definition"? Do you mean: Define the process for determining which roles have what responsibilities for which SCs?

I don't understand what the decision tree is. Sorry, but I can't imagine what you're thinking of. Maybe it needs a rough draft start so we're all on the same page...

And I think Deliverables can be simplified to just:
> * Deliverables
> ** Success Criteria-Role table (and single page views)

**Comment by dboudreau** [comment]
@slhenry - The decision tree part is answered [in another issue](https://github.com/w3c/wai-roles-responsbilities/issues/5), so let's focus on the process definition here.

By "process definition" what we mean is defining the approach we will use to create/curate our content for each role and why we come up with this approach. The decision tree is one tool to help stakeholders achieve the understanding. It is **much more** than just a data table. ;)

**Comment by dboudreau** [comment]
Based on today's call, I suggest closing this issue as well.
