### ISSUE TITLE
[ED][Project Plan] out of scope clarity

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-roles-responsbilities#8]
> Domain training or documentation for role

Not sure what this means, but it doesn't matter much since it's out of scope. ;-)

**Comment by orvalle** [comment]
"Domain training" means training roles on topics in their domain. Many success criteria cover best practices that should be known to professionals in roles. We will expect they are familiar with these and will not spend any time providing training in their specialty - just supplement it with a11y details they need to know.

**Comment by dboudreau** [comment]
Agree with @orvalle. that being said, yes, it's part of the out of scope section, so if you have a preference for another way to word this, we're all ears. :)

**Comment by dboudreau** [comment]
@slhenry - Changed it to "Role-specific training or documentation on accessibility". If this is satisfactory, please close issue.

**Comment by shawna-slh** [comment]
thanks
